name = "client"
version = "0.0.1"
target = "javascript"

gleam = ">= 1.5.1"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.6.1 and < 5.0.0"
lustre_http = ">= 0.5.2 and < 1.0.0"
modem = ">= 2.0.1 and < 3.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
plinth = ">= 0.4.15 and < 1.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
birl = ">= 1.7.1 and < 2.0.0"
lustre_pipes = { path = "../../../lustre_pipes" }
lustre_omnistate = { path = "../../../lustre_omnistate" }
shared = { path = "../shared" }
decode = ">= 0.4.1 and < 1.0.0"
gluid = ">= 1.0.0 and < 2.0.0"
lustre_websocket = ">= 0.7.6 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.0 and < 2.0.0"

